### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by L-O-G-A-N** [TerbiumOS/webOS#14]
How can I host this on my local machine?
I don't want to use a website because my school will just block it but if you can tell me how to run it on a local host I can run it on a chromebook

**Comment by qDread-dev** [comment]
I would like to do this too!

**Comment by Itzswdm** [comment]
ok so basically, I dont think you can do that But I have a solution for the blocking thing
As long as its not blocked to begin with you can get a Url and Make a html file or Google site with this code 
This will open the thing in a About blank tab so they will never actually get the url of the Actual Proxy site (Because its not in your history just the html file or google site that this button is on) unless they dig through the html code of the html file or the google site



Code:
<button onclick="Func()" class="generated-text" type="button">Click Here!</button>
<script>
function Func() {
    var win = window.open(); var f = win.document.createElement("iframe");  window.focus(); var url = "URL GOES HERE"; if (!url) return; f.style.width = "100%"; f.style.height = "100%"; win.document.body.appendChild(f); f.src=url; win.document.body.style.margin = '0'; f.style.border = 'none'; f.style.margin = '0'; win.document.body.style.height = '100vh'
    }
</script>

**Comment by GamerGoat112** [comment]
make unlimited links
1. Get a link from freenom
2. Change nameservers to cloudflare's
3. Add CNAME record of @ --> c.terbium.ga
4. Change SSL/TLS to Full (not strict)

**Comment by NovaAppsInc** [comment]
Well the new UV broke the ability it seems, but if I could fix it it would go like this

```
npm i
npm start
```

then you would go to `localhost:6969`
